### ISSUE TITLE
[NFR] Add github action

### ISSUE THREAD

**Issue by ruudboon** [jooy2/vutron#177]
It would be great to have an github action that works with this project for easily building and releasing using github actions.
I tried using https://github.com/motrixapp/action-electron-builder but due to different dist path I don't think this will work.

**Comment by ruudboon** [comment]
Fixed it using a different action
```
name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        #[macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: coparse-inc/action-electron-builder@v1.0.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: '--config=buildAssets/builder/config.js'

```
